api_key: https://8188-35-243-203-217.ngrok-free.app
llm_model: ollama
base_url: https://8188-35-243-203-217.ngrok-free.app
llm_model_name: Qwen-QwQ-32b-Pentest-CoT-Q8_0-GGUF
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 1200
proxies: {}
