api_key: dummy
llm_model: openai
base_url: https://5578-35-223-200-49.ngrok-free.app/v1
llm_model_name: /kaggle/working/Qwen3-32B-AWQ
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.7
history_len: 5
timeout: 1200
proxies: {}
