api_key: https://319e-34-72-225-156.ngrok-free.app
llm_model: ollama
base_url: https://319e-34-72-225-156.ngrok-free.app
llm_model_name: hf.co/bartowski/Qwen_QwQ-32B-GGUF:Q2_K
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 1200
proxies: {}
