api_key: https://a430-115-78-13-71.ngrok-free.app
llm_model: ollama
base_url: https://a430-115-78-13-71.ngrok-free.app
llm_model_name: qwq:32b-fp16 
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 1200
proxies: {}
