api_key: http://127.0.0.1:11434
llm_model: ollama
base_url: ''
llm_model_name: deepseek-r1:1.5b_20cpu
embedding_models: maidalun1020/bce-embedding-base_v1
embedding_type: local
context_length: 120000
embedding_url: ''
rerank_model: maidalun1020/bce-reranker-base_v1
temperature: 0.5
history_len: 5
timeout: 600
proxies: {}
